# Generated by Django 4.1.2 on 2022-11-26 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievementcategory',
            options={'verbose_name_plural': 'Achievement categories'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name_plural': 'Project categories'},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name_plural': 'Skill categories'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
    ]
