# Generated by Django 4.1.2 on 2022-11-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='emphasis',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
