# Generated by Django 4.1.2 on 2022-11-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_degree_emphasis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreetype',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
