# Generated by Django 4.1.2 on 2022-11-26 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_degreetype_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='degree',
        ),
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=5)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.college')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='api.department'),
            preserve_default=False,
        ),
    ]
