# Generated by Django 4.1.2 on 2022-11-26 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_course_degree_course_number_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='college',
        ),
        migrations.AddField(
            model_name='degree',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.department'),
            preserve_default=False,
        ),
    ]
