# Generated by Django 4.1.2 on 2022-11-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_degree_college_degree_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='start_date',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
    ]
