# Generated by Django 4.1.2 on 2022-11-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_employment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
